import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Ban, Check, KeyRound, Plus, Search, ShieldCheck, UsersRound, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, type Group, type PermissionCatalog, type Role, type User } from '../api/client';
import { useAuth } from '../hooks/useAuth';
import { FeaturesPanel } from '../components/FeaturesPanel';
import { roleMeta } from '../lib/taskflow';

export function Users() {
  const { user: actor } = useAuth();
  const root = Boolean(actor?.is_root);
  const [users, setUsers] = useState<User[]>([]);
  const [roles, setRoles] = useState<Role[]>([]);
  const [groups, setGroups] = useState<Group[]>([]);
  const [catalog, setCatalog] = useState<PermissionCatalog | null>(null);
  const [tab, setTab] = useState<'users' | 'roles' | 'groups'>('users');
  const [search, setSearch] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [createOpen, setCreateOpen] = useState(false);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState<Role | null>(null);
  const [newRole, setNewRole] = useState('');
  const [newGroup, setNewGroup] = useState('');
  const [access, setAccess] = useState<Awaited<ReturnType<typeof api.getUserAccess>> | null>(null);
  const [accessName, setAccessName] = useState('');
  const [accessUserId, setAccessUserId] = useState<number | null>(null);
  const load = useCallback(async () => {
    const [u, r, c] = await Promise.all([api.getUsers('platform'), api.getRoles(), api.getPermissionCatalog()]);
    setUsers(u); setRoles(r); setCatalog(c);
    if (root) setGroups(await api.getGroups());
  }, [root]);
  useEffect(() => { load().catch(e => setError(e.message)).finally(() => setLoading(false)); }, [load]);
  const run = async (operation: () => Promise<unknown>) => {
    setError(''); setBusy(true);
    try { await operation(); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Не удалось сохранить'); }
    finally { setBusy(false); }
  };
  const create = (event: FormEvent) => {
    event.preventDefault(); void run(async () => { await api.createUser(username, password); setCreateOpen(false); setUsername(''); setPassword(''); });
  };
  const filtered = users.filter(u => u.username.toLowerCase().includes(search.toLowerCase()));
  const canManage = Boolean(root || actor?.permissions?.users_manage);
  return <div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><div className="tf-eyebrow">Управление приложением</div><h2 className="tf-page-title">Пользователи и доступ</h2><p className="tf-page-subtitle">Аккаунты общие для приложения. Работа и роли команды задаются отдельно в каждом пространстве.</p></div>{canManage && <button className="tf-button tf-button-primary" onClick={() => setCreateOpen(true)}><Plus size={16} />Новый пользователь</button>}</header>
    <div className="grid gap-3 sm:grid-cols-3">{[['Аккаунтов', users.length], ['Активных', users.filter(u => u.is_active !== false).length], ['Ожидают смены пароля', users.filter(u => u.must_change_password).length]].map(([label, value]) => <div key={label} className="tf-panel-flat p-4"><span className="text-xs text-[var(--color-muted)]">{label}</span><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div>
    <div className="tf-panel-flat flex flex-wrap gap-2 p-2"><button className={`tf-button ${tab === 'users' ? 'tf-button-primary' : ''}`} onClick={() => setTab('users')}><UsersRound size={15} />Аккаунты</button>{root && <><button className={`tf-button ${tab === 'roles' ? 'tf-button-primary' : ''}`} onClick={() => setTab('roles')}><ShieldCheck size={15} />Роли приложения</button><button className={`tf-button ${tab === 'groups' ? 'tf-button-primary' : ''}`} onClick={() => setTab('groups')}>Группы</button></>}<Link to="/workspace" className="tf-button ml-auto">Команда пространства →</Link></div>
    {error && <div role="alert" className="tf-alert-error">{error}</div>}
    {loading ? <div className="p-10 text-center">Загрузка…</div> : tab === 'users' ? <section className="tf-panel-flat overflow-hidden">
      <div className="flex items-center gap-2 border-b border-[var(--color-border)] p-4"><Search size={16} /><input className="min-w-0 flex-1 bg-transparent outline-none" value={search} onChange={e => setSearch(e.target.value)} placeholder="Найти пользователя" /></div>
      <div className="overflow-x-auto"><table className="tf-table w-full text-sm"><thead><tr><th>Пользователь</th><th>Статус</th><th>Роль приложения</th><th>Действия</th></tr></thead><tbody>{filtered.map(u => <tr key={u.id}><td><span className="font-semibold">{u.username}</span>{u.is_root && <span className="tf-chip ml-2">Суперадмин</span>}{u.id === actor?.id && <span className="ml-2 text-xs text-[var(--color-muted)]">Вы</span>}</td><td><span className={`tf-chip ${u.is_active === false ? 'text-[var(--color-danger)]' : ''}`}>{u.is_active === false ? 'Заблокирован' : u.must_change_password ? 'Временный пароль' : 'Активен'}</span></td><td>{root && !u.is_root ? <select className="tf-input h-9 min-w-40 text-xs" disabled={busy} value={u.roles?.[0]?.id || ''} onChange={e => void run(() => api.setUserRole(u.id, Number(e.target.value)))}><option value="" disabled>Без роли приложения</option>{roles.filter(r => r.name !== 'superadmin').map(r => <option key={r.id} value={r.id}>{roleMeta[r.name]?.label || r.name}</option>)}</select> : u.roles.map(r => roleMeta[r.name]?.label || r.name).join(', ') || 'Участник'}</td><td><div className="flex flex-wrap gap-1">{canManage && <button disabled={busy} className="tf-button h-8 px-2 text-xs" onClick={() => void run(async () => { setAccess(await api.getUserAccess(u.id)); setAccessName(u.username); setAccessUserId(u.is_root ? null : u.id); })}>Доступ</button>}{canManage && !u.is_root && u.id !== actor?.id && <>{(root || actor?.permissions?.users_password_reset) && <button title="Задать временный пароль" disabled={busy} className="tf-button h-8 px-2" onClick={() => { const next = prompt(`Временный пароль для ${u.username} (от 8 символов):`); if (next && next.length >= 8) void run(() => api.setUserPassword(u.id, next)); }}><KeyRound size={14} /></button>}<button title={u.is_active === false ? 'Разблокировать' : 'Заблокировать'} disabled={busy} className="tf-button h-8 px-2" onClick={() => { if (confirm(`${u.is_active === false ? 'Разблокировать' : 'Заблокировать'} ${u.username}?`)) void run(() => api.setUserStatus(u.id, u.is_active === false)); }}>{u.is_active === false ? <Check size={14} /> : <Ban size={14} />}</button></>}</div></td></tr>)}</tbody></table></div>{!filtered.length && <p className="p-8 text-center text-[var(--color-muted)]">Пользователей не найдено</p>}
    </section> : tab === 'roles' ? <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
      <section className="tf-panel-flat space-y-2 p-4"><form className="flex gap-2" onSubmit={e => { e.preventDefault(); void run(async () => { const r = await api.createRole({ name: newRole, permissions: {} }); setRole(r); setNewRole(''); }); }}><input required className="tf-input" placeholder="Название роли" value={newRole} onChange={e => setNewRole(e.target.value)} /><button disabled={busy} className="tf-button"><Plus size={14} /></button></form>{roles.filter(r => r.name !== 'superadmin').map(r => <button key={r.id} className={`tf-button w-full justify-start ${r.id === role?.id ? 'tf-button-primary' : ''}`} onClick={() => setRole({ ...r, permissions: { ...r.permissions } })}>{roleMeta[r.name]?.label || r.name}</button>)}</section>
      <section className="tf-panel-flat p-5">{role ? <><h3 className="text-lg font-bold">{roleMeta[role.name]?.label || role.name}</h3><p className="tf-page-subtitle mb-4">Права приложения действуют глобально. Рабочие права назначаются в ролях пространства. Новые разрешения добавляются выключенными.</p><div className="space-y-4">{catalog?.groups.filter(g => g.scope === 'app').map(g => <div key={g.id}><h4 className="mb-2 text-xs font-bold uppercase text-[var(--color-muted)]">{g.title}</h4>{g.items.map(item => <label key={item.key} className="flex items-start gap-3 rounded-xl p-2 hover:bg-[var(--color-surface-2)]"><input className="mt-1" type="checkbox" checked={Boolean(role.permissions[item.key])} onChange={e => setRole({ ...role, permissions: { ...role.permissions, [item.key]: e.target.checked } })} /><span className="text-sm"><strong>{item.label}</strong><span className="block text-xs text-[var(--color-muted)]">{item.hint}</span></span></label>)}</div>)}</div><button disabled={busy} className="tf-button tf-button-primary mt-5" onClick={() => void run(() => api.updateRole(role.id, { permissions: role.permissions }))}>Сохранить роль</button></> : <p className="p-8 text-center text-[var(--color-muted)]">Выберите роль или создайте новую</p>}</section>
    </div> : <section className="tf-panel-flat space-y-4 p-5"><h3 className="font-bold">Группы пользователей</h3><p className="tf-page-subtitle">Группы объединяют аккаунты. Глобальные права групп не открывают чужие пространства.</p><form className="flex gap-2" onSubmit={e => { e.preventDefault(); void run(async () => { await api.createGroup({ name: newGroup, permissions: {} }); setNewGroup(''); }); }}><input required className="tf-input" placeholder="Название группы" value={newGroup} onChange={e => setNewGroup(e.target.value)} /><button disabled={busy} className="tf-button">Добавить</button></form>{groups.map(g => <details key={g.id} className="rounded-xl border border-[var(--color-border)] p-4"><summary className="cursor-pointer font-semibold">{g.name} · {g.user_ids?.length || 0}</summary><div className="mt-3 grid gap-2 sm:grid-cols-3">{users.filter(u => !u.is_root).map(u => <label key={u.id} className="flex gap-2 text-sm"><input type="checkbox" disabled={busy} checked={g.user_ids?.includes(u.id) || false} onChange={e => void run(() => api.setGroupMembers(g.id, e.target.checked ? [...(g.user_ids || []), u.id] : (g.user_ids || []).filter(id => id !== u.id)))} />{u.username}</label>)}</div></details>)}</section>}
    {createOpen && <div className="tf-modal-backdrop" onClick={() => setCreateOpen(false)}><form className="tf-modal-shell w-full max-w-md space-y-4 p-6" role="dialog" aria-modal="true" aria-label="Новый пользователь" onClick={e => e.stopPropagation()} onSubmit={create}><div className="flex justify-between"><h3 className="text-xl font-bold">Новый пользователь</h3><button type="button" aria-label="Закрыть" onClick={() => setCreateOpen(false)}><X /></button></div><p className="tf-page-subtitle">Создайте аккаунт, затем назначьте роль приложения и пригласите его в нужные пространства.</p><label className="block text-sm">Логин<input autoComplete="off" className="tf-input mt-1" minLength={2} maxLength={100} required value={username} onChange={e => setUsername(e.target.value)} /></label><label className="block text-sm">Временный пароль<input className="tf-input mt-1" autoComplete="new-password" type="password" minLength={8} required value={password} onChange={e => setPassword(e.target.value)} /></label><p className="text-xs text-[var(--color-muted)]">При первом входе пользователь обязательно сменит пароль. Пространства автоматически не назначаются.</p>{error && <p role="alert" className="tf-alert-error">{error}</p>}<button disabled={busy} className="tf-button tf-button-primary w-full">{busy ? 'Создание…' : 'Создать аккаунт'}</button></form></div>}
    {access && <div className="tf-modal-backdrop" onClick={() => setAccess(null)}><section role="dialog" aria-modal="true" aria-label="Доступ пользователя" className="tf-modal-shell w-full max-w-xl space-y-4 p-6" onClick={e => e.stopPropagation()}><div className="flex justify-between"><h3 className="text-xl font-bold">Доступ: {accessName}</h3><button aria-label="Закрыть" onClick={() => setAccess(null)}><X /></button></div><p className="tf-page-subtitle">Права берутся из роли приложения и роли в конкретном пространстве. Отключённые модули ограничивают рабочие действия.</p><h4 className="font-semibold">Приложение</h4><div className="flex flex-wrap gap-1">{Object.entries(access.app_permissions).filter(([, v]) => v).map(([key]) => <span className="tf-chip" key={key}>{key === 'all' ? 'Полный доступ суперадмина' : catalog?.groups.flatMap(g => g.items).find(i => i.key === key)?.label || key}</span>)}</div>{access.spaces.map(space => <div key={space.id} className="rounded-xl border border-[var(--color-border)] p-3"><strong>{space.name}</strong><span className="tf-chip ml-2">{space.rank}</span><div className="mt-2 flex flex-wrap gap-1">{Object.entries(space.permissions || {}).filter(([, v]) => v).map(([key]) => <span key={key} className={`tf-chip ${space.features[key] === false ? 'line-through opacity-50' : ''}`}>{catalog?.groups.flatMap(g => g.items).find(i => i.key === key)?.label || key}</span>)}</div></div>)}{!access.spaces.length && <p className="text-sm text-[var(--color-muted)]">В пространства не приглашён</p>}{root && accessUserId != null && <FeaturesPanel scope="user" targetId={accessUserId} title="Доступность функций для пользователя" description="Персональный переключатель разрешает использовать уже выданные права. Он не добавляет членство или права и не обходит отключённый модуль либо глобальный запрет. После возвращения глобально отключённой функции включите её здесь явно." />}</section></div>}
  </div>;
}
